import libtcodpy as tcod

MAX_FPS = 20

SCREEN_WIDTH = 64
SCREEN_HEIGHT = 30

CAMERA_WIDTH, CAMERA_HEIGHT = 41, 16

MAP_WIDTH, MAP_HEIGHT = CAMERA_WIDTH, CAMERA_HEIGHT
ROOM_MAX_SIZE = 13
ROOM_MIN_SIZE = 6
MAX_ROOMS = 10
MAX_ROOM_MONSTERS = 5
MAX_ROOM_ITEMS = 5

FOV_ALGO = 0
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 20

RIGHT_PANEL_WIDTH = SCREEN_WIDTH - CAMERA_WIDTH
BAR_WIDTH = 18

BOTTOM_PANEL_HEIGHT = SCREEN_HEIGHT - CAMERA_HEIGHT
BOTTOM_PANEL_WIDTH = MAP_WIDTH
MSG_X = 20
MSG_WIDTH = BOTTOM_PANEL_WIDTH - MSG_X
MSG_HEIGHT = BOTTOM_PANEL_HEIGHT - 1

MOUSE_HIGHLIGHT_COLOR = tcod.Color(100, 100, 255)

BULLET_LIFE = 15

# if on, players and mobs can move diagonally
DIAGONAL_MOVEMENT = True

INVENTORY_WIDTH = SCREEN_WIDTH / 2

DAMAGE_EFFECT_FADE = 20

VICTORY_DISTANCE = 200

GAME_NAME = 'Rogue of Duty'
